/*
 * Copyright (c) 2021. All Rights Reserved License
 *
 * Coded by HypherionMC based on code originally created by MCrafterzz. Code used with written permission
 */

package me.hypherionmc.mcrafterzzreborn.modelements;

import me.hypherionmc.mcrafterzzreborn.Registry;
import me.hypherionmc.mcrafterzzreborn.config.Config;
import me.hypherionmc.mcrafterzzreborn.items.*;
import me.hypherionmc.mcrafterzzreborn.util.ModUtil;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;

import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModElementsToolsArmour {
    public static Item.ToolMaterial opTool = EnumHelper.addToolMaterial("op", 4, 0, 100.0F, 96.0F, 100);
    public static Item.ToolMaterial amethystTool = EnumHelper.addToolMaterial("amethyst", 4, 2000, 9.0F, 4.0F, 15);
    public static Item.ToolMaterial jadeTool = EnumHelper.addToolMaterial("jade", 4, 2000, 9.0F, 4.0F, 15);
    public static Item.ToolMaterial copperTool = EnumHelper.addToolMaterial("copper", 1, 170, 5.0F, 1.0F, 15);
    public static Item.ToolMaterial bronzeTool = EnumHelper.addToolMaterial("bronze", 2, 250, 6.5F, 2.0F, 15);
    public static ItemArmor.ArmorMaterial amethystArmour;
    public static ItemArmor.ArmorMaterial jadeArmour;
    public static ItemArmor.ArmorMaterial copperArmour;
    public static ItemArmor.ArmorMaterial bronzeArmour;
    public static Item copper_sword;
    public static Item bronze_sword;
    public static Item jade_sword;
    public static Item amethyst_sword;
    public static Item stone_bow;
    public static Item iron_bow;
    public static Item gold_bow;
    public static Item diamond_bow;
    public static Item copper_bow;
    public static Item bronze_bow;
    public static Item jade_bow;
    public static Item amethyst_bow;
    public static Item op_bow;
    public static Item stone_shield;
    public static Item iron_shield;
    public static Item gold_shield;
    public static Item diamond_shield;
    public static Item copper_shield;
    public static Item bronze_shield;
    public static Item jade_shield;
    public static Item amethyst_shield;
    public static Item copper_PickAxe;
    public static Item bronze_PickAxe;
    public static Item jade_PickAxe;
    public static Item amethyst_PickAxe;
    public static Item copper_axe;
    public static Item bronze_axe;
    public static Item jade_axe;
    public static Item amethyst_axe;
    public static Item copper_shovel;
    public static Item bronze_shovel;
    public static Item jade_shovel;
    public static Item amethyst_shovel;
    public static Item copper_hoe;
    public static Item bronze_hoe;
    public static Item jade_hoe;
    public static Item amethyst_hoe;
    public static Item diamond_MultiTool;
    public static Item copper_MultiTool;
    public static Item bronze_MultiTool;
    public static Item jade_MultiTool;
    public static Item amethyst_MultiTool;
    public static Item op_MultiTool;
    public static Item wooden_hammer;
    public static Item stone_hammer;
    public static Item iron_hammer;
    public static Item gold_hammer;
    public static Item diamond_hammer;
    public static Item copper_hammer;
    public static Item bronze_hammer;
    public static Item jade_hammer;
    public static Item amethyst_hammer;
    public static Item wooden_scythe;
    public static Item stone_scythe;
    public static Item iron_scythe;
    public static Item gold_scythe;
    public static Item diamond_scythe;
    public static Item copper_scythe;
    public static Item bronze_scythe;
    public static Item jade_scythe;
    public static Item amethyst_scythe;
    public static Item wooden_shears;
    public static Item stone_shears;
    public static Item iron_shears;
    public static Item gold_shears;
    public static Item diamond_shears;
    public static Item copper_shears;
    public static Item bronze_shears;
    public static Item jade_shears;
    public static Item amethyst_shears;
    public static Item flint_and_wood;
    public static Item flint_and_stone;
    public static Item flint_and_iron;
    public static Item flint_and_gold;
    public static Item flint_and_diamond;
    public static Item flint_and_copper;
    public static Item flint_and_bronze;
    public static Item flint_and_jade;
    public static Item flint_and_amethyst;
    public static Item copper_helmet;
    public static Item copper_chestplate;
    public static Item copper_leggings;
    public static Item copper_boots;
    public static Item bronze_helmet;
    public static Item bronze_chestplate;
    public static Item bronze_leggings;
    public static Item bronze_boots;
    public static Item jade_helmet;
    public static Item jade_chestplate;
    public static Item jade_leggings;
    public static Item jade_boots;
    public static Item amethyst_helmet;
    public static Item amethyst_chestplate;
    public static Item amethyst_leggings;
    public static Item amethyst_boots;
    public static Item portable_furnace;

    public ModElementsToolsArmour() {
    }

    public static void createBlocksAndItems() {
        portable_furnace = (new PortableFurnace()).setTranslationKey("portable_furnace");
        copper_sword = (new Sword(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_sword").setCreativeTab(ModElements.creativeTabTools);
        bronze_sword = (new Sword(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_sword").setCreativeTab(ModElements.creativeTabTools);
        jade_sword = (new Sword(jadeTool, ModElements.jade)).setTranslationKey("jade_sword").setCreativeTab(ModElements.creativeTabTools);
        amethyst_sword = (new Sword(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_sword").setCreativeTab(ModElements.creativeTabTools);
        stone_bow = (new Bow(132, Item.getItemFromBlock(Blocks.STONE))).setTranslationKey("stone_bow").setCreativeTab(ModElements.creativeTabTools);
        iron_bow = (new Bow(238, Items.IRON_INGOT)).setTranslationKey("iron_bow").setCreativeTab(ModElements.creativeTabTools);
        gold_bow = (new Bow(275, Items.GOLD_INGOT)).setTranslationKey("gold_bow").setCreativeTab(ModElements.creativeTabTools);
        diamond_bow = (new Bow(1562, Items.DIAMOND)).setTranslationKey("diamond_bow").setCreativeTab(ModElements.creativeTabTools);
        copper_bow = (new Bow(170, ModElements.copper_ingot)).setTranslationKey("copper_bow").setCreativeTab(ModElements.creativeTabTools);
        bronze_bow = (new Bow(250, ModElements.bronze_ingot)).setTranslationKey("bronze_bow").setCreativeTab(ModElements.creativeTabTools);
        jade_bow = (new Bow(2000, ModElements.jade)).setTranslationKey("jade_bow").setCreativeTab(ModElements.creativeTabTools);
        amethyst_bow = (new Bow(2000, ModElements.amethyst)).setTranslationKey("amethyst_bow").setCreativeTab(ModElements.creativeTabTools);
        op_bow = (new Bow(0, ModElements.amethyst)).setTranslationKey("op_bow").setCreativeTab(ModElements.creativeTabTools);
        stone_shield = (new Shield(132, "stone_shield", ModElements.creativeTabTools)).setTranslationKey("stone_shield");
        iron_shield = (new Shield(238, "iron_shield", ModElements.creativeTabTools)).setTranslationKey("iron_shield");
        gold_shield = (new Shield(275, "gold_shield", ModElements.creativeTabTools)).setTranslationKey("gold_shield");
        diamond_shield = (new Shield(1562, "diamond_shield", ModElements.creativeTabTools)).setTranslationKey("diamond_shield");
        copper_shield = (new Shield(170, "copper_shield", ModElements.creativeTabTools)).setTranslationKey("copper_shield");
        bronze_shield = (new Shield(250, "bronze_shield", ModElements.creativeTabTools)).setTranslationKey("bronze_shield");
        jade_shield = (new Shield(2000, "jade_shield", ModElements.creativeTabTools)).setTranslationKey("jade_shield");
        amethyst_shield = (new Shield(2000, "amethyst_shield", ModElements.creativeTabTools)).setTranslationKey("amethyst_shield");
        copper_PickAxe = (new PickAxe(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_PickAxe").setCreativeTab(ModElements.creativeTabTools);
        bronze_PickAxe = (new PickAxe(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_PickAxe").setCreativeTab(ModElements.creativeTabTools);
        jade_PickAxe = (new PickAxe(jadeTool, ModElements.jade)).setTranslationKey("jade_PickAxe").setCreativeTab(ModElements.creativeTabTools);
        amethyst_PickAxe = (new PickAxe(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_PickAxe").setCreativeTab(ModElements.creativeTabTools);
        copper_axe = (new Axe(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_axe").setCreativeTab(ModElements.creativeTabTools);
        bronze_axe = (new Axe(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_axe").setCreativeTab(ModElements.creativeTabTools);
        jade_axe = (new Axe(jadeTool, ModElements.jade)).setTranslationKey("jade_axe").setCreativeTab(ModElements.creativeTabTools);
        amethyst_axe = (new Axe(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_axe").setCreativeTab(ModElements.creativeTabTools);
        copper_shovel = (new Shovel(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_shovel").setCreativeTab(ModElements.creativeTabTools);
        bronze_shovel = (new Shovel(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_shovel").setCreativeTab(ModElements.creativeTabTools);
        jade_shovel = (new Shovel(jadeTool, ModElements.jade)).setTranslationKey("jade_shovel").setCreativeTab(ModElements.creativeTabTools);
        amethyst_shovel = (new Shovel(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_shovel").setCreativeTab(ModElements.creativeTabTools);
        copper_hoe = (new Hoe(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_hoe").setCreativeTab(ModElements.creativeTabTools);
        bronze_hoe = (new Hoe(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_hoe").setCreativeTab(ModElements.creativeTabTools);
        jade_hoe = (new Hoe(jadeTool, ModElements.jade)).setTranslationKey("jade_hoe").setCreativeTab(ModElements.creativeTabTools);
        amethyst_hoe = (new Hoe(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_hoe").setCreativeTab(ModElements.creativeTabTools);
        diamond_MultiTool = (new MultiTool(Item.ToolMaterial.DIAMOND, Items.DIAMOND)).setTranslationKey("diamond_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        copper_MultiTool = (new MultiTool(copperTool, ModElements.copper_ingot)).setTranslationKey("copper_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        bronze_MultiTool = (new MultiTool(bronzeTool, ModElements.bronze_ingot)).setTranslationKey("bronze_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        jade_MultiTool = (new MultiTool(jadeTool, ModElements.jade)).setTranslationKey("jade_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        amethyst_MultiTool = (new MultiTool(amethystTool, ModElements.amethyst)).setTranslationKey("amethyst_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        op_MultiTool = (new MultiTool(opTool, ModElements.amethyst)).setTranslationKey("op_MultiTool").setCreativeTab(ModElements.creativeTabTools);
        wooden_hammer = (new Hammer(Item.ToolMaterial.WOOD, 59)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("wooden_hammer");
        stone_hammer = (new Hammer(Item.ToolMaterial.STONE, 132)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("stone_hammer");
        iron_hammer = (new Hammer(Item.ToolMaterial.IRON, 238)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("iron_hammer");
        gold_hammer = (new Hammer(Item.ToolMaterial.GOLD, 275)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("gold_hammer");
        diamond_hammer = (new Hammer(Item.ToolMaterial.DIAMOND, 1562)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("diamond_hammer");
        copper_hammer = (new Hammer(copperTool, 170)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("copper_hammer");
        bronze_hammer = (new Hammer(bronzeTool, 250)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("bronze_hammer");
        jade_hammer = (new Hammer(bronzeTool, 2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("jade_hammer");
        amethyst_hammer = (new Hammer(bronzeTool, 2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("amethyst_hammer");
        wooden_scythe = (new Scythe(Item.ToolMaterial.WOOD, 59)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("wooden_scythe");
        stone_scythe = (new Scythe(Item.ToolMaterial.STONE, 132)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("stone_scythe");
        iron_scythe = (new Scythe(Item.ToolMaterial.IRON, 238)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("iron_scythe");
        gold_scythe = (new Scythe(Item.ToolMaterial.GOLD, 275)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("gold_scythe");
        diamond_scythe = (new Scythe(Item.ToolMaterial.DIAMOND, 1562)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("diamond_scythe");
        copper_scythe = (new Scythe(copperTool, 170)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("copper_scythe");
        bronze_scythe = (new Scythe(bronzeTool, 250)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("bronze_scythe");
        jade_scythe = (new Scythe(bronzeTool, 2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("jade_scythe");
        amethyst_scythe = (new Scythe(bronzeTool, 2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("amethyst_scythe");
        wooden_shears = (new Shears(0, 59, Item.getItemFromBlock(Blocks.PLANKS))).setTranslationKey("wooden_shears").setCreativeTab(ModElements.creativeTabTools);
        stone_shears = (new Shears(0, 132, Item.getItemFromBlock(Blocks.STONE))).setTranslationKey("stone_shears").setCreativeTab(ModElements.creativeTabTools);
        gold_shears = (new Shears(1, 275, Items.GOLD_INGOT)).setTranslationKey("gold_shears").setCreativeTab(ModElements.creativeTabTools);
        diamond_shears = (new Shears(2, 1562, Items.DIAMOND)).setTranslationKey("diamond_shears").setCreativeTab(ModElements.creativeTabTools);
        copper_shears = (new Shears(1, 170, ModElements.copper_ingot)).setTranslationKey("copper_shears").setCreativeTab(ModElements.creativeTabTools);
        bronze_shears = (new Shears(1, 250, ModElements.bronze_ingot)).setTranslationKey("bronze_shears").setCreativeTab(ModElements.creativeTabTools);
        jade_shears = (new Shears(3, 2000, ModElements.jade)).setTranslationKey("jade_shears").setCreativeTab(ModElements.creativeTabTools);
        amethyst_shears = (new Shears(3, 2000, ModElements.amethyst)).setTranslationKey("amethyst_shears").setCreativeTab(ModElements.creativeTabTools);
        flint_and_wood = (new FlintAndIngot(59)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_wood");
        flint_and_stone = (new FlintAndIngot(132)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_stone");
        flint_and_gold = (new FlintAndIngot(275)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_gold");
        flint_and_diamond = (new FlintAndIngot(1562)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_diamond");
        flint_and_copper = (new FlintAndIngot(170)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_copper");
        flint_and_bronze = (new FlintAndIngot(250)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_bronze");
        flint_and_jade = (new FlintAndIngot(2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_jade");
        flint_and_amethyst = (new FlintAndIngot(2000)).setCreativeTab(ModElements.creativeTabTools).setTranslationKey("flint_and_amethyst");
        copper_helmet = (new Armour(copperArmour, 1, EntityEquipmentSlot.HEAD, ModElements.copper_ingot)).setTranslationKey("copper_helmet").setCreativeTab(ModElements.creativeTabTools);
        copper_chestplate = (new Armour(copperArmour, 1, EntityEquipmentSlot.CHEST, ModElements.copper_ingot)).setTranslationKey("copper_chestplate").setCreativeTab(ModElements.creativeTabTools);
        copper_leggings = (new Armour(copperArmour, 2, EntityEquipmentSlot.LEGS, ModElements.copper_ingot)).setTranslationKey("copper_leggings").setCreativeTab(ModElements.creativeTabTools);
        copper_boots = (new Armour(copperArmour, 1, EntityEquipmentSlot.FEET, ModElements.copper_ingot)).setTranslationKey("copper_boots").setCreativeTab(ModElements.creativeTabTools);
        bronze_helmet = (new Armour(bronzeArmour, 1, EntityEquipmentSlot.HEAD, ModElements.bronze_ingot)).setTranslationKey("bronze_helmet").setCreativeTab(ModElements.creativeTabTools);
        bronze_chestplate = (new Armour(bronzeArmour, 1, EntityEquipmentSlot.CHEST, ModElements.bronze_ingot)).setTranslationKey("bronze_chestplate").setCreativeTab(ModElements.creativeTabTools);
        bronze_leggings = (new Armour(bronzeArmour, 2, EntityEquipmentSlot.LEGS, ModElements.bronze_ingot)).setTranslationKey("bronze_leggings").setCreativeTab(ModElements.creativeTabTools);
        bronze_boots = (new Armour(bronzeArmour, 1, EntityEquipmentSlot.FEET, ModElements.bronze_ingot)).setTranslationKey("bronze_boots").setCreativeTab(ModElements.creativeTabTools);
        jade_helmet = (new Armour(jadeArmour, 1, EntityEquipmentSlot.HEAD, ModElements.jade)).setTranslationKey("jade_helmet").setCreativeTab(ModElements.creativeTabTools);
        jade_chestplate = (new Armour(jadeArmour, 1, EntityEquipmentSlot.CHEST, ModElements.jade)).setTranslationKey("jade_chestplate").setCreativeTab(ModElements.creativeTabTools);
        jade_leggings = (new Armour(jadeArmour, 2, EntityEquipmentSlot.LEGS, ModElements.jade)).setTranslationKey("jade_leggings").setCreativeTab(ModElements.creativeTabTools);
        jade_boots = (new Armour(jadeArmour, 1, EntityEquipmentSlot.FEET, ModElements.jade)).setTranslationKey("jade_boots").setCreativeTab(ModElements.creativeTabTools);
        amethyst_helmet = (new Armour(amethystArmour, 1, EntityEquipmentSlot.HEAD, ModElements.amethyst)).setTranslationKey("amethyst_helmet").setCreativeTab(ModElements.creativeTabTools);
        amethyst_chestplate = (new Armour(amethystArmour, 1, EntityEquipmentSlot.CHEST, ModElements.amethyst)).setTranslationKey("amethyst_chestplate").setCreativeTab(ModElements.creativeTabTools);
        amethyst_leggings = (new Armour(amethystArmour, 2, EntityEquipmentSlot.LEGS, ModElements.amethyst)).setTranslationKey("amethyst_leggings").setCreativeTab(ModElements.creativeTabTools);
        amethyst_boots = (new Armour(amethystArmour, 1, EntityEquipmentSlot.FEET, ModElements.amethyst)).setTranslationKey("amethyst_boots").setCreativeTab(ModElements.creativeTabTools);
    }

    public static void registerItemsAndBlocks() {

        Registry.registerItem(portable_furnace, portable_furnace.getTranslationKey().substring(5));
        Registry.registerItem(copper_sword, copper_sword.getTranslationKey().substring(5));
        Registry.registerItem(bronze_sword, bronze_sword.getTranslationKey().substring(5));
        Registry.registerItem(jade_sword, jade_sword.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_sword, amethyst_sword.getTranslationKey().substring(5));
        Registry.registerItem(stone_bow, stone_bow.getTranslationKey().substring(5));
        Registry.registerItem(iron_bow, iron_bow.getTranslationKey().substring(5));
        Registry.registerItem(gold_bow, gold_bow.getTranslationKey().substring(5));
        Registry.registerItem(diamond_bow, diamond_bow.getTranslationKey().substring(5));
        Registry.registerItem(copper_bow, copper_bow.getTranslationKey().substring(5));
        Registry.registerItem(bronze_bow, bronze_bow.getTranslationKey().substring(5));
        Registry.registerItem(jade_bow, jade_bow.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_bow, amethyst_bow.getTranslationKey().substring(5));
        Registry.registerItem(op_bow, op_bow.getTranslationKey().substring(5));
        Registry.registerItem(stone_shield, stone_shield.getTranslationKey().substring(5));
        Registry.registerItem(iron_shield, iron_shield.getTranslationKey().substring(5));
        Registry.registerItem(gold_shield, gold_shield.getTranslationKey().substring(5));
        Registry.registerItem(diamond_shield, diamond_shield.getTranslationKey().substring(5));
        Registry.registerItem(copper_shield, copper_shield.getTranslationKey().substring(5));
        Registry.registerItem(bronze_shield, bronze_shield.getTranslationKey().substring(5));
        Registry.registerItem(jade_shield, jade_shield.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_shield, amethyst_shield.getTranslationKey().substring(5));
        Registry.registerItem(copper_PickAxe, copper_PickAxe.getTranslationKey().substring(5));
        Registry.registerItem(bronze_PickAxe, bronze_PickAxe.getTranslationKey().substring(5));
        Registry.registerItem(jade_PickAxe, jade_PickAxe.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_PickAxe, amethyst_PickAxe.getTranslationKey().substring(5));
        Registry.registerItem(copper_axe, copper_axe.getTranslationKey().substring(5));
        Registry.registerItem(bronze_axe, bronze_axe.getTranslationKey().substring(5));
        Registry.registerItem(jade_axe, jade_axe.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_axe, amethyst_axe.getTranslationKey().substring(5));
        Registry.registerItem(copper_shovel, copper_shovel.getTranslationKey().substring(5));
        Registry.registerItem(bronze_shovel, bronze_shovel.getTranslationKey().substring(5));
        Registry.registerItem(jade_shovel, jade_shovel.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_shovel, amethyst_shovel.getTranslationKey().substring(5));
        Registry.registerItem(copper_hoe, copper_hoe.getTranslationKey().substring(5));
        Registry.registerItem(bronze_hoe, bronze_hoe.getTranslationKey().substring(5));
        Registry.registerItem(jade_hoe, jade_hoe.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_hoe, amethyst_hoe.getTranslationKey().substring(5));
        Registry.registerItem(diamond_MultiTool, diamond_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(copper_MultiTool, copper_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(bronze_MultiTool, bronze_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(jade_MultiTool, jade_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_MultiTool, amethyst_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(op_MultiTool, op_MultiTool.getTranslationKey().substring(5));
        Registry.registerItem(wooden_hammer, wooden_hammer.getTranslationKey().substring(5));
        Registry.registerItem(stone_hammer, stone_hammer.getTranslationKey().substring(5));
        Registry.registerItem(iron_hammer, iron_hammer.getTranslationKey().substring(5));
        Registry.registerItem(gold_hammer, gold_hammer.getTranslationKey().substring(5));
        Registry.registerItem(diamond_hammer, diamond_hammer.getTranslationKey().substring(5));
        Registry.registerItem(copper_hammer, copper_hammer.getTranslationKey().substring(5));
        Registry.registerItem(bronze_hammer, bronze_hammer.getTranslationKey().substring(5));
        Registry.registerItem(jade_hammer, jade_hammer.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_hammer, amethyst_hammer.getTranslationKey().substring(5));
        Registry.registerItem(wooden_scythe, wooden_scythe.getTranslationKey().substring(5));
        Registry.registerItem(stone_scythe, stone_scythe.getTranslationKey().substring(5));
        Registry.registerItem(iron_scythe, iron_scythe.getTranslationKey().substring(5));
        Registry.registerItem(gold_scythe, gold_scythe.getTranslationKey().substring(5));
        Registry.registerItem(diamond_scythe, diamond_scythe.getTranslationKey().substring(5));
        Registry.registerItem(copper_scythe, copper_scythe.getTranslationKey().substring(5));
        Registry.registerItem(bronze_scythe, bronze_scythe.getTranslationKey().substring(5));
        Registry.registerItem(jade_scythe, jade_scythe.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_scythe, amethyst_scythe.getTranslationKey().substring(5));
        Registry.registerItem(wooden_shears, wooden_shears.getTranslationKey().substring(5));
        Registry.registerItem(stone_shears, stone_shears.getTranslationKey().substring(5));
        Registry.registerItem(gold_shears, gold_shears.getTranslationKey().substring(5));
        Registry.registerItem(diamond_shears, diamond_shears.getTranslationKey().substring(5));
        Registry.registerItem(copper_shears, copper_shears.getTranslationKey().substring(5));
        Registry.registerItem(bronze_shears, bronze_shears.getTranslationKey().substring(5));
        Registry.registerItem(jade_shears, jade_shears.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_shears, amethyst_shears.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_wood, flint_and_wood.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_stone, flint_and_stone.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_gold, flint_and_gold.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_diamond, flint_and_diamond.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_copper, flint_and_copper.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_bronze, flint_and_bronze.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_jade, flint_and_jade.getTranslationKey().substring(5));
        Registry.registerItem(flint_and_amethyst, flint_and_amethyst.getTranslationKey().substring(5));
        Registry.registerItem(copper_helmet, copper_helmet.getTranslationKey().substring(5));
        Registry.registerItem(copper_chestplate, copper_chestplate.getTranslationKey().substring(5));
        Registry.registerItem(copper_leggings, copper_leggings.getTranslationKey().substring(5));
        Registry.registerItem(copper_boots, copper_boots.getTranslationKey().substring(5));
        Registry.registerItem(bronze_helmet, bronze_helmet.getTranslationKey().substring(5));
        Registry.registerItem(bronze_chestplate, bronze_chestplate.getTranslationKey().substring(5));
        Registry.registerItem(bronze_leggings, bronze_leggings.getTranslationKey().substring(5));
        Registry.registerItem(bronze_boots, bronze_boots.getTranslationKey().substring(5));
        Registry.registerItem(jade_helmet, jade_helmet.getTranslationKey().substring(5));
        Registry.registerItem(jade_chestplate, jade_chestplate.getTranslationKey().substring(5));
        Registry.registerItem(jade_leggings, jade_leggings.getTranslationKey().substring(5));
        Registry.registerItem(jade_boots, jade_boots.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_helmet, amethyst_helmet.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_chestplate, amethyst_chestplate.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_leggings, amethyst_leggings.getTranslationKey().substring(5));
        Registry.registerItem(amethyst_boots, amethyst_boots.getTranslationKey().substring(5));
    }

    public static void registerRenders() {

        Registry.registerRenderItem(portable_furnace);
        Registry.registerRenderItem(copper_sword);
        Registry.registerRenderItem(bronze_sword);
        Registry.registerRenderItem(jade_sword);
        Registry.registerRenderItem(amethyst_sword);
        Registry.registerRenderItem(stone_bow);
        Registry.registerRenderItem(iron_bow);
        Registry.registerRenderItem(gold_bow);
        Registry.registerRenderItem(diamond_bow);
        Registry.registerRenderItem(copper_bow);
        Registry.registerRenderItem(bronze_bow);
        Registry.registerRenderItem(jade_bow);
        Registry.registerRenderItem(amethyst_bow);
        Registry.registerRenderItem(op_bow);
        Registry.registerRenderItem(stone_shield);
        Registry.registerRenderItem(iron_shield);
        Registry.registerRenderItem(gold_shield);
        Registry.registerRenderItem(diamond_shield);
        Registry.registerRenderItem(copper_shield);
        Registry.registerRenderItem(bronze_shield);
        Registry.registerRenderItem(jade_shield);
        Registry.registerRenderItem(amethyst_shield);
        Registry.registerRenderItem(copper_PickAxe);
        Registry.registerRenderItem(bronze_PickAxe);
        Registry.registerRenderItem(jade_PickAxe);
        Registry.registerRenderItem(amethyst_PickAxe);
        Registry.registerRenderItem(copper_axe);
        Registry.registerRenderItem(bronze_axe);
        Registry.registerRenderItem(jade_axe);
        Registry.registerRenderItem(amethyst_axe);
        Registry.registerRenderItem(copper_shovel);
        Registry.registerRenderItem(bronze_shovel);
        Registry.registerRenderItem(jade_shovel);
        Registry.registerRenderItem(amethyst_shovel);
        Registry.registerRenderItem(copper_hoe);
        Registry.registerRenderItem(bronze_hoe);
        Registry.registerRenderItem(jade_hoe);
        Registry.registerRenderItem(amethyst_hoe);
        Registry.registerRenderItem(diamond_MultiTool);
        Registry.registerRenderItem(copper_MultiTool);
        Registry.registerRenderItem(bronze_MultiTool);
        Registry.registerRenderItem(jade_MultiTool);
        Registry.registerRenderItem(amethyst_MultiTool);
        Registry.registerRenderItem(op_MultiTool);
        Registry.registerRenderItem(wooden_hammer);
        Registry.registerRenderItem(stone_hammer);
        Registry.registerRenderItem(iron_hammer);
        Registry.registerRenderItem(gold_hammer);
        Registry.registerRenderItem(diamond_hammer);
        Registry.registerRenderItem(copper_hammer);
        Registry.registerRenderItem(bronze_hammer);
        Registry.registerRenderItem(jade_hammer);
        Registry.registerRenderItem(amethyst_hammer);
        Registry.registerRenderItem(wooden_scythe);
        Registry.registerRenderItem(stone_scythe);
        Registry.registerRenderItem(iron_scythe);
        Registry.registerRenderItem(gold_scythe);
        Registry.registerRenderItem(diamond_scythe);
        Registry.registerRenderItem(copper_scythe);
        Registry.registerRenderItem(bronze_scythe);
        Registry.registerRenderItem(jade_scythe);
        Registry.registerRenderItem(amethyst_scythe);
        Registry.registerRenderItem(wooden_shears);
        Registry.registerRenderItem(stone_shears);
        Registry.registerRenderItem(gold_shears);
        Registry.registerRenderItem(diamond_shears);
        Registry.registerRenderItem(copper_shears);
        Registry.registerRenderItem(bronze_shears);
        Registry.registerRenderItem(jade_shears);
        Registry.registerRenderItem(amethyst_shears);
        Registry.registerRenderItem(flint_and_wood);
        Registry.registerRenderItem(flint_and_stone);
        Registry.registerRenderItem(flint_and_gold);
        Registry.registerRenderItem(flint_and_diamond);
        Registry.registerRenderItem(flint_and_copper);
        Registry.registerRenderItem(flint_and_bronze);
        Registry.registerRenderItem(flint_and_jade);
        Registry.registerRenderItem(flint_and_amethyst);
        Registry.registerRenderItem(copper_helmet);
        Registry.registerRenderItem(copper_chestplate);
        Registry.registerRenderItem(copper_leggings);
        Registry.registerRenderItem(copper_boots);
        Registry.registerRenderItem(bronze_helmet);
        Registry.registerRenderItem(bronze_chestplate);
        Registry.registerRenderItem(bronze_leggings);
        Registry.registerRenderItem(bronze_boots);
        Registry.registerRenderItem(jade_helmet);
        Registry.registerRenderItem(jade_chestplate);
        Registry.registerRenderItem(jade_leggings);
        Registry.registerRenderItem(jade_boots);
        Registry.registerRenderItem(amethyst_helmet);
        Registry.registerRenderItem(amethyst_chestplate);
        Registry.registerRenderItem(amethyst_leggings);
        Registry.registerRenderItem(amethyst_boots);
    }

    public static void setupRepairItemForToolsAndArmour() {
        copperTool.setRepairItem(new ItemStack(ModElements.copper_ingot));
        copperArmour.repairMaterial = new ItemStack(ModElements.copper_ingot);
        bronzeTool.setRepairItem(new ItemStack(ModElements.bronze_ingot));
        bronzeArmour.repairMaterial = new ItemStack(ModElements.bronze_ingot);
        jadeTool.setRepairItem(new ItemStack(ModElements.jade));
        jadeArmour.repairMaterial = new ItemStack(ModElements.jade);
        amethystTool.setRepairItem(new ItemStack(ModElements.amethyst));
        amethystArmour.repairMaterial = new ItemStack(ModElements.amethyst);
    }

    public static void crafting() {
        if (Config.crafting) {
            
            GameRegistry.addShapedRecipe(new ItemStack(copper_sword).getItem().getRegistryName(), null, new ItemStack(copper_sword), new Object[]{" C ", " C ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_sword).getItem().getRegistryName(), null, new ItemStack(copper_sword), new Object[]{"C  ", "C  ", "S  ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_sword).getItem().getRegistryName(), null, new ItemStack(copper_sword), new Object[]{"  C", "  C", "  S", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_sword).getItem().getRegistryName(), null, new ItemStack(bronze_sword), new Object[]{" B ", " B ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_sword).getItem().getRegistryName(), null, new ItemStack(bronze_sword), new Object[]{"B  ", "B  ", "S  ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_sword).getItem().getRegistryName(), null, new ItemStack(bronze_sword), new Object[]{"  B", "  B", "  S", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_sword).getItem().getRegistryName(), null, new ItemStack(jade_sword), new Object[]{" J ", " J ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_sword).getItem().getRegistryName(), null, new ItemStack(jade_sword), new Object[]{"J  ", "J  ", "S  ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_sword).getItem().getRegistryName(), null, new ItemStack(jade_sword), new Object[]{"  J", "  J", "  S", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_sword).getItem().getRegistryName(), null, new ItemStack(amethyst_sword), new Object[]{" A ", " A ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_sword).getItem().getRegistryName(), null, new ItemStack(amethyst_sword), new Object[]{"A  ", "A  ", "S  ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_sword).getItem().getRegistryName(), null, new ItemStack(amethyst_sword), new Object[]{"  A", "  A", "  S", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapelessRecipe(new ItemStack(stone_bow, 1).getItem().getRegistryName(), null, new ItemStack(stone_bow, 1), ModUtil.objectToIngredient(new Object[]{Blocks.STONE, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(iron_bow, 1).getItem().getRegistryName(), null, new ItemStack(iron_bow, 1), ModUtil.objectToIngredient(new Object[]{Items.IRON_INGOT, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(gold_bow, 1).getItem().getRegistryName(), null, new ItemStack(gold_bow, 1), ModUtil.objectToIngredient(new Object[]{Items.GOLD_INGOT, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(diamond_bow, 1).getItem().getRegistryName(), null, new ItemStack(diamond_bow, 1), ModUtil.objectToIngredient(new Object[]{Items.DIAMOND, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(copper_bow, 1).getItem().getRegistryName(), null, new ItemStack(copper_bow, 1), ModUtil.objectToIngredient(new Object[]{ModElements.copper_ingot, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(bronze_bow, 1).getItem().getRegistryName(), null, new ItemStack(bronze_bow, 1), ModUtil.objectToIngredient(new Object[]{ModElements.bronze_ingot, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(jade_bow, 1).getItem().getRegistryName(), null, new ItemStack(jade_bow, 1), ModUtil.objectToIngredient(new Object[]{ModElements.jade, Items.BOW}));
            GameRegistry.addShapelessRecipe(new ItemStack(amethyst_bow, 1).getItem().getRegistryName(), null, new ItemStack(amethyst_bow, 1), ModUtil.objectToIngredient(new Object[]{ModElements.amethyst, Items.BOW}));
            GameRegistry.addShapedRecipe(new ItemStack(op_bow).getItem().getRegistryName(), null, new ItemStack(op_bow), new Object[]{"AAA", "ABA", "AAA", 'A', ModElements.amethyst_block, 'B', Items.BOW});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shield).getItem().getRegistryName(), null, new ItemStack(stone_shield), new Object[]{"SSS", "SSS", " S ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(iron_shield).getItem().getRegistryName(), null, new ItemStack(iron_shield), new Object[]{"III", "III", " I ", 'I', Items.IRON_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shield).getItem().getRegistryName(), null, new ItemStack(gold_shield), new Object[]{"GGG", "GGG", " G ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shield).getItem().getRegistryName(), null, new ItemStack(diamond_shield), new Object[]{"DDD", "DDD", " D ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shield).getItem().getRegistryName(), null, new ItemStack(copper_shield), new Object[]{"CCC", "CCC", " C ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shield).getItem().getRegistryName(), null, new ItemStack(bronze_shield), new Object[]{"BBB", "BBB", " B ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shield).getItem().getRegistryName(), null, new ItemStack(jade_shield), new Object[]{"JJJ", "JJJ", " J ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shield).getItem().getRegistryName(), null, new ItemStack(amethyst_shield), new Object[]{"AAA", "AAA", " A ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(copper_PickAxe).getItem().getRegistryName(), null, new ItemStack(copper_PickAxe), new Object[]{"CCC", " S ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_PickAxe).getItem().getRegistryName(), null, new ItemStack(bronze_PickAxe), new Object[]{"BBB", " S ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_PickAxe).getItem().getRegistryName(), null, new ItemStack(jade_PickAxe), new Object[]{"JJJ", " S ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_PickAxe).getItem().getRegistryName(), null, new ItemStack(amethyst_PickAxe), new Object[]{"AAA", " S ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_axe).getItem().getRegistryName(), null, new ItemStack(copper_axe), new Object[]{"CC ", "CS ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_axe).getItem().getRegistryName(), null, new ItemStack(copper_axe), new Object[]{" CC", " SC", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_axe).getItem().getRegistryName(), null, new ItemStack(copper_axe), new Object[]{" CC", " CS", "  S", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_axe).getItem().getRegistryName(), null, new ItemStack(copper_axe), new Object[]{"CC ", "SC ", "S  ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_axe).getItem().getRegistryName(), null, new ItemStack(bronze_axe), new Object[]{"BB ", "BS ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_axe).getItem().getRegistryName(), null, new ItemStack(bronze_axe), new Object[]{" BB", " SB", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_axe).getItem().getRegistryName(), null, new ItemStack(bronze_axe), new Object[]{" BB", " BS", "  S", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_axe).getItem().getRegistryName(), null, new ItemStack(bronze_axe), new Object[]{"BB ", "SB ", "S  ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_axe).getItem().getRegistryName(), null, new ItemStack(jade_axe), new Object[]{"JJ ", "JS ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_axe).getItem().getRegistryName(), null, new ItemStack(jade_axe), new Object[]{" JJ", " SJ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_axe).getItem().getRegistryName(), null, new ItemStack(jade_axe), new Object[]{" JJ", " JS", "  S", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_axe).getItem().getRegistryName(), null, new ItemStack(jade_axe), new Object[]{"JJ ", "SJ ", "S  ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_axe).getItem().getRegistryName(), null, new ItemStack(amethyst_axe), new Object[]{"AA ", "AS ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_axe).getItem().getRegistryName(), null, new ItemStack(amethyst_axe), new Object[]{" AA", " SA", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_axe).getItem().getRegistryName(), null, new ItemStack(amethyst_axe), new Object[]{" AA", " AS", "  S", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_axe).getItem().getRegistryName(), null, new ItemStack(amethyst_axe), new Object[]{"AA ", "SA ", "S  ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shovel).getItem().getRegistryName(), null, new ItemStack(copper_shovel), new Object[]{" C ", " S ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shovel).getItem().getRegistryName(), null, new ItemStack(copper_shovel), new Object[]{"C  ", "S  ", "S  ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shovel).getItem().getRegistryName(), null, new ItemStack(copper_shovel), new Object[]{"  C", "  S", "  S", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shovel).getItem().getRegistryName(), null, new ItemStack(bronze_shovel), new Object[]{" B ", " S ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shovel).getItem().getRegistryName(), null, new ItemStack(bronze_shovel), new Object[]{"B  ", "S  ", "S  ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shovel).getItem().getRegistryName(), null, new ItemStack(bronze_shovel), new Object[]{"  B", "  S", "  S", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shovel).getItem().getRegistryName(), null, new ItemStack(jade_shovel), new Object[]{" J ", " S ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shovel).getItem().getRegistryName(), null, new ItemStack(jade_shovel), new Object[]{"J  ", "S  ", "S  ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shovel).getItem().getRegistryName(), null, new ItemStack(jade_shovel), new Object[]{"  J", "  S", "  S", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shovel).getItem().getRegistryName(), null, new ItemStack(amethyst_shovel), new Object[]{" A ", " S ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shovel).getItem().getRegistryName(), null, new ItemStack(amethyst_shovel), new Object[]{"A  ", "S  ", "S  ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shovel).getItem().getRegistryName(), null, new ItemStack(amethyst_shovel), new Object[]{"  A", "  S", "  S", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_hoe).getItem().getRegistryName(), null, new ItemStack(copper_hoe), new Object[]{"CC ", " S ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_hoe).getItem().getRegistryName(), null, new ItemStack(copper_hoe), new Object[]{" CC", " S ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_hoe).getItem().getRegistryName(), null, new ItemStack(copper_hoe), new Object[]{"CC ", "S  ", "S  ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_hoe).getItem().getRegistryName(), null, new ItemStack(copper_hoe), new Object[]{" CC", "  S", "  S", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_hoe).getItem().getRegistryName(), null, new ItemStack(bronze_hoe), new Object[]{"BB ", " S ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_hoe).getItem().getRegistryName(), null, new ItemStack(bronze_hoe), new Object[]{" BB", " S ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_hoe).getItem().getRegistryName(), null, new ItemStack(bronze_hoe), new Object[]{"BB ", "S  ", "S  ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_hoe).getItem().getRegistryName(), null, new ItemStack(bronze_hoe), new Object[]{" BB", "  S", "  S", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_hoe).getItem().getRegistryName(), null, new ItemStack(jade_hoe), new Object[]{"JJ ", " S ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_hoe).getItem().getRegistryName(), null, new ItemStack(jade_hoe), new Object[]{" JJ", " S ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_hoe).getItem().getRegistryName(), null, new ItemStack(jade_hoe), new Object[]{"JJ ", "S  ", "S  ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_hoe).getItem().getRegistryName(), null, new ItemStack(jade_hoe), new Object[]{" JJ", "  S", "  S", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_hoe).getItem().getRegistryName(), null, new ItemStack(amethyst_hoe), new Object[]{"AA ", " S ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_hoe).getItem().getRegistryName(), null, new ItemStack(amethyst_hoe), new Object[]{" AA", " S ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_hoe).getItem().getRegistryName(), null, new ItemStack(amethyst_hoe), new Object[]{"AA ", "S  ", "S  ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_hoe).getItem().getRegistryName(), null, new ItemStack(amethyst_hoe), new Object[]{" AA", "  S", "  S", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapelessRecipe(new ItemStack(diamond_MultiTool, 1).getItem().getRegistryName(), null, new ItemStack(diamond_MultiTool, 1), ModUtil.objectToIngredient(new Object[]{Items.DIAMOND_SWORD, Items.DIAMOND_PICKAXE, Items.DIAMOND_AXE, Items.DIAMOND_SHOVEL, Items.DIAMOND_HOE}));
            GameRegistry.addShapelessRecipe(new ItemStack(copper_MultiTool, 1).getItem().getRegistryName(), null, new ItemStack(copper_MultiTool, 1), ModUtil.objectToIngredient(new Object[]{copper_sword, copper_PickAxe, copper_axe, copper_shovel, copper_hoe}));
            GameRegistry.addShapelessRecipe(new ItemStack(bronze_MultiTool, 1).getItem().getRegistryName(), null, new ItemStack(bronze_MultiTool, 1), ModUtil.objectToIngredient(new Object[]{bronze_sword, bronze_PickAxe, bronze_axe, bronze_shovel, bronze_hoe}));
            GameRegistry.addShapelessRecipe(new ItemStack(jade_MultiTool, 1).getItem().getRegistryName(), null, new ItemStack(jade_MultiTool, 1), ModUtil.objectToIngredient(new Object[]{jade_sword, jade_PickAxe, jade_axe, jade_shovel, jade_hoe}));
            GameRegistry.addShapelessRecipe(new ItemStack(amethyst_MultiTool, 1).getItem().getRegistryName(), null, new ItemStack(amethyst_MultiTool, 1), ModUtil.objectToIngredient(new Object[]{amethyst_sword, amethyst_PickAxe, amethyst_axe, amethyst_shovel, amethyst_hoe}));
            GameRegistry.addShapedRecipe(new ItemStack(op_MultiTool).getItem().getRegistryName(), null, new ItemStack(op_MultiTool), new Object[]{"AMA", "MNM", "AMA", 'A', ModElements.amethyst_block, 'M', amethyst_MultiTool, 'N', Items.NETHER_STAR});
            GameRegistry.addShapedRecipe(new ItemStack(op_MultiTool).getItem().getRegistryName(), null, new ItemStack(op_MultiTool), new Object[]{"MAM", "ANA", "MAM", 'A', ModElements.amethyst_block, 'M', amethyst_MultiTool, 'N', Items.NETHER_STAR});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_hammer).getItem().getRegistryName(), null, new ItemStack(wooden_hammer), new Object[]{"WWW", "WWW", " S ", 'W', Blocks.PLANKS, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(stone_hammer).getItem().getRegistryName(), null, new ItemStack(stone_hammer), new Object[]{"BBB", "BBB", " S ", 'B', Blocks.STONE, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(iron_hammer).getItem().getRegistryName(), null, new ItemStack(iron_hammer), new Object[]{"III", "III", " S ", 'I', Items.IRON_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(gold_hammer).getItem().getRegistryName(), null, new ItemStack(gold_hammer), new Object[]{"GGG", "GGG", " S ", 'G', Items.GOLD_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_hammer).getItem().getRegistryName(), null, new ItemStack(diamond_hammer), new Object[]{"DDD", "DDD", " S ", 'D', Items.DIAMOND, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_hammer).getItem().getRegistryName(), null, new ItemStack(copper_hammer), new Object[]{"CCC", "CCC", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_hammer).getItem().getRegistryName(), null, new ItemStack(bronze_hammer), new Object[]{"BBB", "BBB", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_hammer).getItem().getRegistryName(), null, new ItemStack(jade_hammer), new Object[]{"JJJ", "JJJ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_hammer).getItem().getRegistryName(), null, new ItemStack(amethyst_hammer), new Object[]{"AAA", "AAA", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_scythe).getItem().getRegistryName(), null, new ItemStack(wooden_scythe), new Object[]{"WWW", "WS ", " S ", 'W', Blocks.PLANKS, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_scythe).getItem().getRegistryName(), null, new ItemStack(wooden_scythe), new Object[]{"WWW", " SW", " S ", 'W', Blocks.PLANKS, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(stone_scythe).getItem().getRegistryName(), null, new ItemStack(stone_scythe), new Object[]{"BBB", "BS ", " S ", 'B', Blocks.STONE, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(stone_scythe).getItem().getRegistryName(), null, new ItemStack(stone_scythe), new Object[]{"BBB", " SB", " S ", 'B', Blocks.STONE, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(iron_scythe).getItem().getRegistryName(), null, new ItemStack(iron_scythe), new Object[]{"III", "IS ", " S ", 'I', Items.IRON_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(iron_scythe).getItem().getRegistryName(), null, new ItemStack(iron_scythe), new Object[]{"III", " SI", " S ", 'I', Items.IRON_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(gold_scythe).getItem().getRegistryName(), null, new ItemStack(gold_scythe), new Object[]{"GGG", "GS ", " S ", 'G', Items.GOLD_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(gold_scythe).getItem().getRegistryName(), null, new ItemStack(gold_scythe), new Object[]{"GGG", " SG", " S ", 'G', Items.GOLD_INGOT, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_scythe).getItem().getRegistryName(), null, new ItemStack(diamond_scythe), new Object[]{"DDD", "DS ", " S ", 'D', Items.DIAMOND, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_scythe).getItem().getRegistryName(), null, new ItemStack(diamond_scythe), new Object[]{"DDD", " SD", " S ", 'D', Items.DIAMOND, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_scythe).getItem().getRegistryName(), null, new ItemStack(copper_scythe), new Object[]{"CCC", "CS ", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(copper_scythe).getItem().getRegistryName(), null, new ItemStack(copper_scythe), new Object[]{"CCC", " SC", " S ", 'C', ModElements.copper_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_scythe).getItem().getRegistryName(), null, new ItemStack(bronze_scythe), new Object[]{"BBB", "BS ", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_scythe).getItem().getRegistryName(), null, new ItemStack(bronze_scythe), new Object[]{"BBB", " SB", " S ", 'B', ModElements.bronze_ingot, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_scythe).getItem().getRegistryName(), null, new ItemStack(jade_scythe), new Object[]{"JJJ", "JS ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(jade_scythe).getItem().getRegistryName(), null, new ItemStack(jade_scythe), new Object[]{"JJJ", " SJ", " S ", 'J', ModElements.jade, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_scythe).getItem().getRegistryName(), null, new ItemStack(amethyst_scythe), new Object[]{"AAA", "AS ", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_scythe).getItem().getRegistryName(), null, new ItemStack(amethyst_scythe), new Object[]{"AAA", " SA", " S ", 'A', ModElements.amethyst, 'S', Items.STICK});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"W  ", " W ", "   ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{" W ", "  W", "   ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{" W ", "  W", "   ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"W  ", " W ", "   ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"   ", "W  ", " W ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"   ", " W ", "  W", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"   ", " W ", "  W", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(wooden_shears).getItem().getRegistryName(), null, new ItemStack(wooden_shears), new Object[]{"   ", "W  ", " W ", 'W', Blocks.PLANKS});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"S  ", " S ", "   ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{" S ", "  S", "   ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{" S ", "  S", "   ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"S  ", " S ", "   ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"   ", "S  ", " S ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"   ", " S ", "  S", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"   ", " S ", "  S", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(stone_shears).getItem().getRegistryName(), null, new ItemStack(stone_shears), new Object[]{"   ", "S  ", " S ", 'S', Blocks.STONE});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"G  ", " G ", "   ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{" G ", "  G", "   ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{" G ", "  G", "   ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"G  ", " G ", "   ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"   ", "G  ", " G ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"   ", " G ", "  G", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"   ", " G ", "  G", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"   ", "G  ", " G ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(gold_shears).getItem().getRegistryName(), null, new ItemStack(gold_shears), new Object[]{"G  ", " G ", "   ", 'G', Items.GOLD_INGOT});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{" D ", "  D", "   ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{" D ", "  D", "   ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{"D  ", " D ", "   ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{"   ", "D  ", " D ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{"   ", " D ", "  D", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{"   ", " D ", "  D", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(diamond_shears).getItem().getRegistryName(), null, new ItemStack(diamond_shears), new Object[]{"   ", "D  ", " D ", 'D', Items.DIAMOND});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{" C ", "  C", "   ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{" C ", "  C", "   ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{"C  ", " C ", "   ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{"   ", "C  ", " C ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{"   ", " C ", "  C", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{"   ", " C ", "  C", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_shears).getItem().getRegistryName(), null, new ItemStack(copper_shears), new Object[]{"   ", "C  ", " C ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{" B ", "  B", "   ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{" B ", "  B", "   ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{"B  ", " B ", "   ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{"   ", "B  ", " B ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{"   ", " B ", "  B", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{"   ", " B ", "  B", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_shears).getItem().getRegistryName(), null, new ItemStack(bronze_shears), new Object[]{"   ", "B  ", " B ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{" J ", "  J", "   ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{" J ", "  J", "   ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{"J  ", " J ", "   ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{"   ", "J  ", " J ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{"   ", " J ", "  J", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{"   ", " J ", "  J", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_shears).getItem().getRegistryName(), null, new ItemStack(jade_shears), new Object[]{"   ", "J  ", " J ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{" A ", "  A", "   ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{" A ", "  A", "   ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{"A  ", " A ", "   ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{"   ", "A  ", " A ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{"   ", " A ", "  A", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{"   ", " A ", "  A", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_shears).getItem().getRegistryName(), null, new ItemStack(amethyst_shears), new Object[]{"   ", "A  ", " A ", 'A', ModElements.amethyst});
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_wood, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_wood, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(Blocks.PLANKS, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_stone, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_stone, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(Blocks.STONE, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_gold, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_gold, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(Items.GOLD_INGOT, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_diamond, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_diamond, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(Items.DIAMOND, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_copper, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_copper, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(ModElements.copper_ingot, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_bronze, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_bronze, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(ModElements.bronze_ingot, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_jade, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_jade, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(ModElements.jade, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapelessRecipe(new ItemStack(flint_and_amethyst, 1).getItem().getRegistryName(), null, new ItemStack(flint_and_amethyst, 1), ModUtil.objectToIngredient(new Object[]{new ItemStack(ModElements.amethyst, 1), new ItemStack(Items.FLINT, 1)}));
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_helmet).getItem().getRegistryName(), null, new ItemStack(amethyst_helmet), new Object[]{"AAA", "A A", "   ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_helmet).getItem().getRegistryName(), null, new ItemStack(amethyst_helmet), new Object[]{"   ", "AAA", "A A", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_chestplate).getItem().getRegistryName(), null, new ItemStack(amethyst_chestplate), new Object[]{"A A", "AAA", "AAA", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_leggings).getItem().getRegistryName(), null, new ItemStack(amethyst_leggings), new Object[]{"AAA", "A A", "A A", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_boots).getItem().getRegistryName(), null, new ItemStack(amethyst_boots), new Object[]{"   ", "A A", "A A", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(amethyst_boots).getItem().getRegistryName(), null, new ItemStack(amethyst_boots), new Object[]{"A A", "A A", "   ", 'A', ModElements.amethyst});
            GameRegistry.addShapedRecipe(new ItemStack(jade_helmet).getItem().getRegistryName(), null, new ItemStack(jade_helmet), new Object[]{"JJJ", "J J", "   ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_helmet).getItem().getRegistryName(), null, new ItemStack(jade_helmet), new Object[]{"   ", "JJJ", "J J", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_chestplate).getItem().getRegistryName(), null, new ItemStack(jade_chestplate), new Object[]{"J J", "JJJ", "JJJ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_leggings).getItem().getRegistryName(), null, new ItemStack(jade_leggings), new Object[]{"JJJ", "J J", "J J", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_boots).getItem().getRegistryName(), null, new ItemStack(jade_boots), new Object[]{"   ", "J J", "J J", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(jade_boots).getItem().getRegistryName(), null, new ItemStack(jade_boots), new Object[]{"J J", "J J", "   ", 'J', ModElements.jade});
            GameRegistry.addShapedRecipe(new ItemStack(copper_helmet).getItem().getRegistryName(), null, new ItemStack(copper_helmet), new Object[]{"CCC", "C C", "   ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_helmet).getItem().getRegistryName(), null, new ItemStack(copper_helmet), new Object[]{"   ", "CCC", "C C", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_chestplate).getItem().getRegistryName(), null, new ItemStack(copper_chestplate), new Object[]{"C C", "CCC", "CCC", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_leggings).getItem().getRegistryName(), null, new ItemStack(copper_leggings), new Object[]{"CCC", "C C", "C C", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_boots).getItem().getRegistryName(), null, new ItemStack(copper_boots), new Object[]{"   ", "C C", "C C", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(copper_boots).getItem().getRegistryName(), null, new ItemStack(copper_boots), new Object[]{"C C", "C C", "   ", 'C', ModElements.copper_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_helmet).getItem().getRegistryName(), null, new ItemStack(bronze_helmet), new Object[]{"BBB", "B B", "   ", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_helmet).getItem().getRegistryName(), null, new ItemStack(bronze_helmet), new Object[]{"   ", "BBB", "B B", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_chestplate).getItem().getRegistryName(), null, new ItemStack(bronze_chestplate), new Object[]{"B B", "BBB", "BBB", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_leggings).getItem().getRegistryName(), null, new ItemStack(bronze_leggings), new Object[]{"BBB", "B B", "B B", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_boots).getItem().getRegistryName(), null, new ItemStack(bronze_boots), new Object[]{"   ", "B B", "B B", 'B', ModElements.bronze_ingot});
            GameRegistry.addShapedRecipe(new ItemStack(bronze_boots).getItem().getRegistryName(), null, new ItemStack(bronze_boots), new Object[]{"B B", "B B", "   ", 'B', ModElements.bronze_ingot});
        }

    }

    static {
        amethystArmour = EnumHelper.addArmorMaterial("amethyst", "mm:amethyst", 42, new int[]{4, 9, 5, 4}, 15, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 0.0F);
        jadeArmour = EnumHelper.addArmorMaterial("jade", "mm:jade", 42, new int[]{4, 9, 5, 4}, 15, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 0.0F);
        copperArmour = EnumHelper.addArmorMaterial("copper", "mm:copper", 13, new int[]{2, 7, 4, 1}, 15, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
        bronzeArmour = EnumHelper.addArmorMaterial("bronze", "mm:bronze", 16, new int[]{3, 6, 4, 2}, 15, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
    }
}
