/*
 * Copyright (c) 2021. MIT License License
 *
 * Coded by HypherionMC based on code originally created by MCrafterzz. Code used with written permission
 */

package me.hypherionmc.mcrafterzzreborn.init;

import me.hypherionmc.mcrafterzzreborn.ModConstants;
import me.hypherionmc.mcrafterzzreborn.blocks.*;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.util.DamageSource;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;


public class ModBlocks {

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ModConstants.MODID);

    //Blocks
    public static DamageSource death_block = (new DamageSource("deathBlock")).setDamageBypassesArmor().setDamageIsAbsolute();

    /**
     * Simple Blocks
     */
    public static RegistryObject<Block> amethyst_ore = BLOCKS.register("amethyst_ore", () -> new SimpleBlock("amethyst_ore", Material.ROCK, SoundType.METAL, "pickaxe", 3, MaterialColor.STONE, ModTabs.creativeTabWorld, 5.5F, 30.0F));
    public static RegistryObject<Block> jade_ore = BLOCKS.register("jade_ore", () -> new SimpleBlock("jade_ore", Material.ROCK, SoundType.METAL, "pickaxe", 3, MaterialColor.STONE, ModTabs.creativeTabWorld, 5.5F, 30.0F));
    public static RegistryObject<Block> copper_ore = BLOCKS.register("copper_ore", () -> new SimpleBlock("copper_ore", Material.ROCK, SoundType.METAL, "pickaxe", 1, MaterialColor.STONE, ModTabs.creativeTabWorld, 4.5F, 25.0F));
    public static RegistryObject<Block> tin_ore = BLOCKS.register("tin_ore", () -> new SimpleBlock("tin_ore", Material.ROCK, SoundType.METAL, "pickaxe", 1, MaterialColor.STONE, ModTabs.creativeTabWorld, 4.5F, 25.0F));
    public static RegistryObject<Block> amethyst_block = BLOCKS.register("amethyst_block", () -> new SimpleBlock("amethyst_block", Material.ROCK, SoundType.METAL, "pickaxe", 3, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> jade_block = BLOCKS.register("jade_block", () -> new SimpleBlock("jade_block", Material.ROCK, SoundType.METAL, "pickaxe", 3, MaterialColor.EMERALD, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> copper_block = BLOCKS.register("copper_block", () -> new SimpleBlock("copper_block", Material.ROCK, SoundType.METAL, "pickaxe", 1, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> tin_block = BLOCKS.register("tin_block", () -> new SimpleBlock("tin_block", Material.ROCK, SoundType.METAL, "pickaxe", 1, MaterialColor.IRON, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> bronze_block = BLOCKS.register("bronze_block", () -> new SimpleBlock("bronze_block", Material.ROCK, SoundType.METAL, "pickaxe", 2, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_barrier = BLOCKS.register("glowing_barrier", () -> new SimpleBlock("glowing_barrier", Material.BARRIER, SoundType.GLASS, "pickaxe", 0, true, 1.0F, true, ModTabs.creativeTabMapMaking, 1.8E7F));
    public static RegistryObject<Block> glowing_air = BLOCKS.register("glowing_air", () -> new GlowingAir("glowing_air", Material.BARRIER, ModTabs.creativeTabMapMaking, 1.8E7F));
    public static RegistryObject<Block> block_of_death = BLOCKS.register("block_of_death", () -> new DeathBlock("block_of_death", Material.ROCK, ModTabs.creativeTabMapMaking, 10.0F, 5.0F));
    public static RegistryObject<Block> null_block = BLOCKS.register("null_block", () -> new NullBlock("null_block", ModTabs.creativeTab, 1000000.0F));
    public static RegistryObject<Block> scaffolding_block = BLOCKS.register("scaffolding_block", () -> new SimpleBlock("scaffolding_block", Material.SAND, SoundType.WOOD, true, MaterialColor.WOOD, ModTabs.creativeTabBuilding));
    public static RegistryObject<Block> colour_changing_wool = BLOCKS.register("colour_changing_wool", () -> new ColorBlock("colour_changing_wool", Material.WOOL, SoundType.CLOTH, (String)null, 0, MaterialColor.WOOL, ModTabs.creativeTabBuilding, 0.8F, 4.0F));
    public static RegistryObject<Block> colour_changing_clay = BLOCKS.register("colour_changing_clay", () -> new ColorBlock("colour_changing_clay", Material.CLAY, SoundType.STONE, "pickaxe", 0, MaterialColor.CLAY, ModTabs.creativeTabBuilding, 1.25F, 30.0F));
    public static RegistryObject<Block> colour_changing_glass = BLOCKS.register("colour_changing_glass", () -> new ColorChangingClass("colour_changing_glass", Material.GLASS, SoundType.GLASS, MaterialColor.AIR, ModTabs.creativeTabBuilding, 0.3F, 1.5F));
    public static RegistryObject<Block> basalt = BLOCKS.register("basalt", () -> new SimpleBlock("basalt", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> basalt_bricks = BLOCKS.register("basalt_bricks", () -> new SimpleBlock("basalt_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> polished_basalt = BLOCKS.register("polished_basalt", () -> new SimpleBlock("polished_basalt", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> polished_stone = BLOCKS.register("polished_stone", () -> new SimpleBlock("polished_stone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.STONE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> granite_bricks = BLOCKS.register("granite_bricks", () -> new SimpleBlock("granite_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> andesite_bricks = BLOCKS.register("andesite_bricks", () -> new SimpleBlock("andesite_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.STONE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> diorite_bricks = BLOCKS.register("diorite_bricks", () -> new SimpleBlock("diorite_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> sandy_bricks = BLOCKS.register("sandy_bricks", () -> new SimpleBlock("sandy_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.SAND, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> sandy_stone_bricks = BLOCKS.register("sandy_stone_bricks", () -> new SimpleBlock("sandy_stone_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.SAND, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> dark_nether_bricks = BLOCKS.register("dark_nether_bricks", () -> new SimpleBlock("dark_nether_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));


    /**
     * Pressure Plates
     */
    public static RegistryObject<Block> diamond_pressure_plate = BLOCKS.register("diamond_pressure_plate", () -> new PressurePlate("diamond_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> copper_pressure_plate = BLOCKS.register("copper_pressure_plate", () -> new PressurePlate("copper_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> tin_pressure_plate = BLOCKS.register("tin_pressure_plate", () -> new PressurePlate("tin_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> bronze_pressure_plate = BLOCKS.register("bronze_pressure_plate", () -> new PressurePlate("bronze_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> jade_pressure_plate = BLOCKS.register("jade_pressure_plate", () -> new PressurePlate("jade_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> amethyst_pressure_plate = BLOCKS.register("amethyst_pressure_plate", () -> new PressurePlate("amethyst_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> emerald_pressure_plate = BLOCKS.register("emerald_pressure_plate", () -> new PressurePlate("emerald_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> quartz_pressure_plate = BLOCKS.register("quartz_pressure_plate", () -> new PressurePlate("quartz_pressure_plate", Material.ROCK, SoundType.METAL, "pickaxe", 0, ModTabs.creativeTabBuilding, 0.8F, 4.0F));
    public static RegistryObject<Block> invisible_pressure_plate = BLOCKS.register("invisible_pressure_plate", () -> new PressurePlate("invisible_pressure_plate", Material.BARRIER, true, true, ModTabs.creativeTabMapMaking, 1.8E7F, 0f));

    /**
     * Bars
     */
    public static RegistryObject<Block> stone_bars = BLOCKS.register("stone_bars", () -> new Bars("stone_bars", Material.ROCK, SoundType.STONE, "pickaxe", 0, true, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> gold_bars = BLOCKS.register("gold_bars", () -> new Bars("gold_bars", Material.ROCK, SoundType.METAL, "pickaxe", 1, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> diamond_bars = BLOCKS.register("diamond_bars", () -> new Bars("diamond_bars", Material.ROCK, SoundType.METAL, "pickaxe", 2, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> copper_bars = BLOCKS.register("copper_bars", () -> new Bars("copper_bars", Material.ROCK, SoundType.METAL, "pickaxe", 1, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> tin_bars = BLOCKS.register("tin_bars", () -> new Bars("tin_bars", Material.ROCK, SoundType.METAL, "pickaxe", 1, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> bronze_bars = BLOCKS.register("bronze_bars", () -> new Bars("bronze_bars", Material.ROCK, SoundType.METAL, "pickaxe", 2, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> jade_bars = BLOCKS.register("jade_bars", () -> new Bars("jade_bars", Material.ROCK, SoundType.METAL, "pickaxe", 3, true, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> amethyst_bars = BLOCKS.register("amethyst_bars", () -> new Bars("amethyst_bars", Material.ROCK, SoundType.METAL, "pickaxe", 3, true, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> emerald_bars = BLOCKS.register("emerald_bars", () -> new Bars("emerald_bars", Material.ROCK, SoundType.METAL, "pickaxe", 2, true, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> quartz_bars = BLOCKS.register("quartz_bars", () -> new Bars("quartz_bars", Material.ROCK, SoundType.METAL, "pickaxe", 0, true, ModTabs.creativeTabBuilding, 0.8F, 4.0F));

    /**
     * Trap Doors
     */
    public static RegistryObject<Block> stone_trapdoor = BLOCKS.register("stone_trapdoor", () -> new ModTrapDoor("stone_trapdoor", Material.ROCK, SoundType.STONE, "pickaxe", 0, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> gold_trapdoor = BLOCKS.register("gold_trapdoor", () -> new ModTrapDoor("gold_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> diamond_trapdoor = BLOCKS.register("diamond_trapdoor", () -> new ModTrapDoor("diamond_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> copper_trapdoor = BLOCKS.register("copper_trapdoor", () -> new ModTrapDoor("copper_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> tin_trapdoor = BLOCKS.register("tin_trapdoor", () -> new ModTrapDoor("tin_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> bronze_trapdoor = BLOCKS.register("bronze_trapdoor", () -> new ModTrapDoor("bronze_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> jade_trapdoor = BLOCKS.register("jade_trapdoor", () -> new ModTrapDoor("jade_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> amethyst_trapdoor = BLOCKS.register("amethyst_trapdoor", () -> new ModTrapDoor("amethyst_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> emerald_trapdoor = BLOCKS.register("emerald_trapdoor", () -> new ModTrapDoor("emerald_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> quartz_trapdoor = BLOCKS.register("quartz_trapdoor", () -> new ModTrapDoor("quartz_trapdoor", Material.ROCK, SoundType.METAL, "pickaxe", 0, ModTabs.creativeTabBuilding, 0.8F, 4.0F));

    /**
     * Buttons
     */
    public static RegistryObject<Block> iron_button = BLOCKS.register("iron_button", () -> new Button("iron_button", false, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> gold_button = BLOCKS.register("gold_button", () -> new Button("gold_button", false, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> diamond_button = BLOCKS.register("diamond_button", () -> new Button("diamond_button", false, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> copper_button = BLOCKS.register("copper_button", () -> new Button("copper_button", false, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> tin_button = BLOCKS.register("tin_button", () -> new Button("tin_button", false, SoundType.METAL, "pickaxe", 1, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> bronze_button = BLOCKS.register("bronze_button", () -> new Button("bronze_button", false, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> jade_button = BLOCKS.register("jade_button", () -> new Button("jade_button", false, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> amethyst_button = BLOCKS.register("amethyst_button", () -> new Button("amethyst_button", false, SoundType.METAL, "pickaxe", 3, ModTabs.creativeTabBuilding, 6.0F, 35.0F));
    public static RegistryObject<Block> emerald_button = BLOCKS.register("emerald_button", () -> new Button("emerald_button", false, SoundType.METAL, "pickaxe", 2, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> quartz_button = BLOCKS.register("quartz_button", () -> new Button("quartz_button", false, SoundType.METAL, "pickaxe", 0, ModTabs.creativeTabBuilding, 0.8F, 4.0F));
    public static RegistryObject<Block> lever_torch = BLOCKS.register("lever_torch", () -> new TorchLever("lever_torch"));
    
    /**
     * Color Blocks
     */
    public static RegistryObject<Block> colour_block_white = BLOCKS.register("colour_block_white", () -> new ColorBlock("colour_block_white", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.IRON, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_light_gray = BLOCKS.register("colour_block_light_gray", () -> new ColorBlock("colour_block_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_gray = BLOCKS.register("colour_block_gray", () -> new ColorBlock("colour_block_gray", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_black = BLOCKS.register("colour_block_black", () -> new ColorBlock("colour_block_black", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_light_blue = BLOCKS.register("colour_block_light_blue", () -> new ColorBlock("colour_block_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_cyan = BLOCKS.register("colour_block_cyan", () -> new ColorBlock("colour_block_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_blue = BLOCKS.register("colour_block_blue", () -> new ColorBlock("colour_block_blue", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_light_green = BLOCKS.register("colour_block_light_green", () -> new ColorBlock("colour_block_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_green = BLOCKS.register("colour_block_green", () -> new ColorBlock("colour_block_green", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_yellow = BLOCKS.register("colour_block_yellow", () -> new ColorBlock("colour_block_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_orange = BLOCKS.register("colour_block_orange", () -> new ColorBlock("colour_block_orange", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_brown = BLOCKS.register("colour_block_brown", () -> new ColorBlock("colour_block_brown", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_magenta = BLOCKS.register("colour_block_magenta", () -> new ColorBlock("colour_block_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_purple = BLOCKS.register("colour_block_purple", () -> new ColorBlock("colour_block_purple", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_red = BLOCKS.register("colour_block_red", () -> new ColorBlock("colour_block_red", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_block_pink = BLOCKS.register("colour_block_pink", () -> new ColorBlock("colour_block_pink", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.PINK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> colour_changing_block = BLOCKS.register("colour_changing_block", () -> new ColorBlock("colour_changing_block", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> seamless_stone_slab = BLOCKS.register("seamless_stone_slab", () -> new SimpleBlock("seamless_stone_slab", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.STONE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> seamless_oak_log = BLOCKS.register("seamless_oak_log", () -> new SimpleBlock("seamless_oak_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_birch_log = BLOCKS.register("seamless_birch_log", () -> new SimpleBlock("seamless_birch_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_spruce_log = BLOCKS.register("seamless_spruce_log", () -> new SimpleBlock("seamless_spruce_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_jungle_log = BLOCKS.register("seamless_jungle_log", () -> new SimpleBlock("seamless_jungle_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_acacia_log = BLOCKS.register("seamless_acacia_log", () -> new SimpleBlock("seamless_acacia_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_dark_oak_log = BLOCKS.register("seamless_dark_oak_log", () -> new SimpleBlock("seamless_dark_oak_log", Material.WOOD, SoundType.WOOD, "axe", 0, MaterialColor.WOOD, ModTabs.creativeTabBuilding, 2.0F, 10.0F));
    public static RegistryObject<Block> seamless_smooth_sandstone = BLOCKS.register("seamless_smooth_sandstone", () -> new SimpleBlock("seamless_smooth_sandstone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.SAND, ModTabs.creativeTabBuilding, 0.8F, 4.0F));
    public static RegistryObject<Block> seamless_smooth_red_sandstone = BLOCKS.register("seamless_smooth_red_sandstone", () -> new SimpleBlock("seamless_smooth_red_sandstone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 0.8F, 4.0F));

    // Fixed Colors
    public static RegistryObject<Block> coloured_stone_bricks_white = BLOCKS.register("coloured_stone_bricks_white", () -> new ColorBlock("coloured_stone_bricks_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_light_gray = BLOCKS.register("coloured_stone_bricks_light_gray", () -> new ColorBlock("coloured_stone_bricks_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_gray = BLOCKS.register("coloured_stone_bricks_gray", () -> new ColorBlock("coloured_stone_bricks_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_black = BLOCKS.register("coloured_stone_bricks_black", () -> new ColorBlock("coloured_stone_bricks_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_light_blue = BLOCKS.register("coloured_stone_bricks_light_blue", () -> new ColorBlock("coloured_stone_bricks_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_cyan = BLOCKS.register("coloured_stone_bricks_cyan", () -> new ColorBlock("coloured_stone_bricks_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_blue = BLOCKS.register("coloured_stone_bricks_blue", () -> new ColorBlock("coloured_stone_bricks_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_light_green = BLOCKS.register("coloured_stone_bricks_light_green", () -> new ColorBlock("coloured_stone_bricks_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_green = BLOCKS.register("coloured_stone_bricks_green", () -> new ColorBlock("coloured_stone_bricks_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_yellow = BLOCKS.register("coloured_stone_bricks_yellow", () -> new ColorBlock("coloured_stone_bricks_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_orange = BLOCKS.register("coloured_stone_bricks_orange", () -> new ColorBlock("coloured_stone_bricks_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_brown = BLOCKS.register("coloured_stone_bricks_brown", () -> new ColorBlock("coloured_stone_bricks_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_magenta = BLOCKS.register("coloured_stone_bricks_magenta", () -> new ColorBlock("coloured_stone_bricks_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_purple = BLOCKS.register("coloured_stone_bricks_purple", () -> new ColorBlock("coloured_stone_bricks_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_red = BLOCKS.register("coloured_stone_bricks_red", () -> new ColorBlock("coloured_stone_bricks_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_bricks_pink = BLOCKS.register("coloured_stone_bricks_pink", () -> new ColorBlock("coloured_stone_bricks_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> colour_changing_stone_bricks = BLOCKS.register("colour_changing_stone_bricks", () -> new ColorBlock("colour_changing_stone_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_white = BLOCKS.register("coloured_stone_white", () -> new ColorBlock("coloured_stone_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_light_gray = BLOCKS.register("coloured_stone_light_gray", () -> new ColorBlock("coloured_stone_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_gray = BLOCKS.register("coloured_stone_gray", () -> new ColorBlock("coloured_stone_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_black = BLOCKS.register("coloured_stone_black", () -> new ColorBlock("coloured_stone_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_light_blue = BLOCKS.register("coloured_stone_light_blue", () -> new ColorBlock("coloured_stone_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_cyan = BLOCKS.register("coloured_stone_cyan", () -> new ColorBlock("coloured_stone_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_blue = BLOCKS.register("coloured_stone_blue", () -> new ColorBlock("coloured_stone_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_light_green = BLOCKS.register("coloured_stone_light_green", () -> new ColorBlock("coloured_stone_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_green = BLOCKS.register("coloured_stone_green", () -> new ColorBlock("coloured_stone_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_yellow = BLOCKS.register("coloured_stone_yellow", () -> new ColorBlock("coloured_stone_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_orange = BLOCKS.register("coloured_stone_orange", () -> new ColorBlock("coloured_stone_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_brown = BLOCKS.register("coloured_stone_brown", () -> new ColorBlock("coloured_stone_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_magenta = BLOCKS.register("coloured_stone_magenta", () -> new ColorBlock("coloured_stone_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_purple = BLOCKS.register("coloured_stone_purple", () -> new ColorBlock("coloured_stone_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_red = BLOCKS.register("coloured_stone_red", () -> new ColorBlock("coloured_stone_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_stone_pink = BLOCKS.register("coloured_stone_pink", () -> new ColorBlock("coloured_stone_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> colour_changing_stone = BLOCKS.register("colour_changing_stone", () -> new ColorBlock("colour_changing_stone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_white = BLOCKS.register("coloured_cobblestone_white", () -> new ColorBlock("coloured_cobblestone_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_light_gray = BLOCKS.register("coloured_cobblestone_light_gray", () -> new ColorBlock("coloured_cobblestone_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_gray = BLOCKS.register("coloured_cobblestone_gray", () -> new ColorBlock("coloured_cobblestone_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_black = BLOCKS.register("coloured_cobblestone_black", () -> new ColorBlock("coloured_cobblestone_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_light_blue = BLOCKS.register("coloured_cobblestone_light_blue", () -> new ColorBlock("coloured_cobblestone_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_cyan = BLOCKS.register("coloured_cobblestone_cyan", () -> new ColorBlock("coloured_cobblestone_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_blue = BLOCKS.register("coloured_cobblestone_blue", () -> new ColorBlock("coloured_cobblestone_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_light_green = BLOCKS.register("coloured_cobblestone_light_green", () -> new ColorBlock("coloured_cobblestone_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_green = BLOCKS.register("coloured_cobblestone_green", () -> new ColorBlock("coloured_cobblestone_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_yellow = BLOCKS.register("coloured_cobblestone_yellow", () -> new ColorBlock("coloured_cobblestone_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_orange = BLOCKS.register("coloured_cobblestone_orange", () -> new ColorBlock("coloured_cobblestone_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_brown = BLOCKS.register("coloured_cobblestone_brown", () -> new ColorBlock("coloured_cobblestone_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_magenta = BLOCKS.register("coloured_cobblestone_magenta", () -> new ColorBlock("coloured_cobblestone_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_purple = BLOCKS.register("coloured_cobblestone_purple", () -> new ColorBlock("coloured_cobblestone_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_red = BLOCKS.register("coloured_cobblestone_red", () -> new ColorBlock("coloured_cobblestone_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> coloured_cobblestone_pink = BLOCKS.register("coloured_cobblestone_pink", () -> new ColorBlock("coloured_cobblestone_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> colour_changing_cobblestone = BLOCKS.register("colour_changing_cobblestone", () -> new ColorBlock("colour_changing_cobblestone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));

    /**
     * Glowing Color Blocks
     */
    public static RegistryObject<Block> glowing_colour_block_white = BLOCKS.register("glowing_colour_block_white", () -> new GlowingColorBlock("glowing_colour_block_white", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.IRON, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_light_gray = BLOCKS.register("glowing_colour_block_light_gray", () -> new GlowingColorBlock("glowing_colour_block_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_gray = BLOCKS.register("glowing_colour_block_gray", () -> new GlowingColorBlock("glowing_colour_block_gray", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_black = BLOCKS.register("glowing_colour_block_black", () -> new GlowingColorBlock("glowing_colour_block_black", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_light_blue = BLOCKS.register("glowing_colour_block_light_blue", () -> new GlowingColorBlock("glowing_colour_block_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_cyan = BLOCKS.register("glowing_colour_block_cyan", () -> new GlowingColorBlock("glowing_colour_block_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_blue = BLOCKS.register("glowing_colour_block_blue", () -> new GlowingColorBlock("glowing_colour_block_blue", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_light_green = BLOCKS.register("glowing_colour_block_light_green", () -> new GlowingColorBlock("glowing_colour_block_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_green = BLOCKS.register("glowing_colour_block_green", () -> new GlowingColorBlock("glowing_colour_block_green", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_yellow = BLOCKS.register("glowing_colour_block_yellow", () -> new GlowingColorBlock("glowing_colour_block_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_orange = BLOCKS.register("glowing_colour_block_orange", () -> new GlowingColorBlock("glowing_colour_block_orange", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_brown = BLOCKS.register("glowing_colour_block_brown", () -> new GlowingColorBlock("glowing_colour_block_brown", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_magenta = BLOCKS.register("glowing_colour_block_magenta", () -> new GlowingColorBlock("glowing_colour_block_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_purple = BLOCKS.register("glowing_colour_block_purple", () -> new GlowingColorBlock("glowing_colour_block_purple", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_red = BLOCKS.register("glowing_colour_block_red", () -> new GlowingColorBlock("glowing_colour_block_red", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.RED, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_block_pink = BLOCKS.register("glowing_colour_block_pink", () -> new GlowingColorBlock("glowing_colour_block_pink", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.PINK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_changing_block = BLOCKS.register("glowing_colour_changing_block", () -> new GlowingColorBlock("glowing_colour_changing_block", Material.ROCK, SoundType.STONE, "pickaxe", 2, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 5.0F, 30.0F));

    // Multi Color
    public static RegistryObject<Block> glowing_coloured_stone_bricks_white = BLOCKS.register("glowing_coloured_stone_bricks_white", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_light_gray = BLOCKS.register("glowing_coloured_stone_bricks_light_gray", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_gray = BLOCKS.register("glowing_coloured_stone_bricks_gray", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_black = BLOCKS.register("glowing_coloured_stone_bricks_black", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_light_blue = BLOCKS.register("glowing_coloured_stone_bricks_light_blue", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_cyan = BLOCKS.register("glowing_coloured_stone_bricks_cyan", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_blue = BLOCKS.register("glowing_coloured_stone_bricks_blue", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_light_green = BLOCKS.register("glowing_coloured_stone_bricks_light_green", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_green = BLOCKS.register("glowing_coloured_stone_bricks_green", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_yellow = BLOCKS.register("glowing_coloured_stone_bricks_yellow", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_orange = BLOCKS.register("glowing_coloured_stone_bricks_orange", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_brown = BLOCKS.register("glowing_coloured_stone_bricks_brown", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_magenta = BLOCKS.register("glowing_coloured_stone_bricks_magenta", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_purple = BLOCKS.register("glowing_coloured_stone_bricks_purple", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_red = BLOCKS.register("glowing_coloured_stone_bricks_red", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_bricks_pink = BLOCKS.register("glowing_coloured_stone_bricks_pink", () -> new GlowingColorBlock("glowing_coloured_stone_bricks_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_colour_changing_stone_bricks = BLOCKS.register("glowing_colour_changing_stone_bricks", () -> new GlowingColorBlock("glowing_colour_changing_stone_bricks", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_white = BLOCKS.register("glowing_coloured_stone_white", () -> new GlowingColorBlock("glowing_coloured_stone_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_light_gray = BLOCKS.register("glowing_coloured_stone_light_gray", () -> new GlowingColorBlock("glowing_coloured_stone_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_gray = BLOCKS.register("glowing_coloured_stone_gray", () -> new GlowingColorBlock("glowing_coloured_stone_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_black = BLOCKS.register("glowing_coloured_stone_black", () -> new GlowingColorBlock("glowing_coloured_stone_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_light_blue = BLOCKS.register("glowing_coloured_stone_light_blue", () -> new GlowingColorBlock("glowing_coloured_stone_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_cyan = BLOCKS.register("glowing_coloured_stone_cyan", () -> new GlowingColorBlock("glowing_coloured_stone_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_blue = BLOCKS.register("glowing_coloured_stone_blue", () -> new GlowingColorBlock("glowing_coloured_stone_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_light_green = BLOCKS.register("glowing_coloured_stone_light_green", () -> new GlowingColorBlock("glowing_coloured_stone_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_green = BLOCKS.register("glowing_coloured_stone_green", () -> new GlowingColorBlock("glowing_coloured_stone_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_yellow = BLOCKS.register("glowing_coloured_stone_yellow", () -> new GlowingColorBlock("glowing_coloured_stone_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_orange = BLOCKS.register("glowing_coloured_stone_orange", () -> new GlowingColorBlock("glowing_coloured_stone_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_brown = BLOCKS.register("glowing_coloured_stone_brown", () -> new GlowingColorBlock("glowing_coloured_stone_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_magenta = BLOCKS.register("glowing_coloured_stone_magenta", () -> new GlowingColorBlock("glowing_coloured_stone_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_purple = BLOCKS.register("glowing_coloured_stone_purple", () -> new GlowingColorBlock("glowing_coloured_stone_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_red = BLOCKS.register("glowing_coloured_stone_red", () -> new GlowingColorBlock("glowing_coloured_stone_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_stone_pink = BLOCKS.register("glowing_coloured_stone_pink", () -> new GlowingColorBlock("glowing_coloured_stone_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));
    public static RegistryObject<Block> glowing_colour_changing_stone = BLOCKS.register("glowing_colour_changing_stone", () -> new GlowingColorBlock("glowing_colour_changing_stone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 1.5F, 30.0F));

    public static RegistryObject<Block> glowing_coloured_cobblestone_white = BLOCKS.register("glowing_coloured_cobblestone_white", () -> new GlowingColorBlock("glowing_coloured_cobblestone_white", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.IRON, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_light_gray = BLOCKS.register("glowing_coloured_cobblestone_light_gray", () -> new GlowingColorBlock("glowing_coloured_cobblestone_light_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_gray = BLOCKS.register("glowing_coloured_cobblestone_gray", () -> new GlowingColorBlock("glowing_coloured_cobblestone_gray", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GRAY, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_black = BLOCKS.register("glowing_coloured_cobblestone_black", () -> new GlowingColorBlock("glowing_coloured_cobblestone_black", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_light_blue = BLOCKS.register("glowing_coloured_cobblestone_light_blue", () -> new GlowingColorBlock("glowing_coloured_cobblestone_light_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.LIGHT_BLUE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_cyan = BLOCKS.register("glowing_coloured_cobblestone_cyan", () -> new GlowingColorBlock("glowing_coloured_cobblestone_cyan", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.CYAN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_blue = BLOCKS.register("glowing_coloured_cobblestone_blue", () -> new GlowingColorBlock("glowing_coloured_cobblestone_blue", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLUE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_light_green = BLOCKS.register("glowing_coloured_cobblestone_light_green", () -> new GlowingColorBlock("glowing_coloured_cobblestone_light_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_green = BLOCKS.register("glowing_coloured_cobblestone_green", () -> new GlowingColorBlock("glowing_coloured_cobblestone_green", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.GREEN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_yellow = BLOCKS.register("glowing_coloured_cobblestone_yellow", () -> new GlowingColorBlock("glowing_coloured_cobblestone_yellow", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.YELLOW, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_orange = BLOCKS.register("glowing_coloured_cobblestone_orange", () -> new GlowingColorBlock("glowing_coloured_cobblestone_orange", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_brown = BLOCKS.register("glowing_coloured_cobblestone_brown", () -> new GlowingColorBlock("glowing_coloured_cobblestone_brown", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BROWN, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_magenta = BLOCKS.register("glowing_coloured_cobblestone_magenta", () -> new GlowingColorBlock("glowing_coloured_cobblestone_magenta", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.MAGENTA, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_purple = BLOCKS.register("glowing_coloured_cobblestone_purple", () -> new GlowingColorBlock("glowing_coloured_cobblestone_purple", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PURPLE, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_red = BLOCKS.register("glowing_coloured_cobblestone_red", () -> new GlowingColorBlock("glowing_coloured_cobblestone_red", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_coloured_cobblestone_pink = BLOCKS.register("glowing_coloured_cobblestone_pink", () -> new GlowingColorBlock("glowing_coloured_cobblestone_pink", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.PINK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));
    public static RegistryObject<Block> glowing_colour_changing_cobblestone = BLOCKS.register("glowing_colour_changing_cobblestone", () -> new GlowingColorBlock("glowing_colour_changing_cobblestone", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabBuilding, 2.0F, 30.0F));

    /**
     * Flowers
     */
    public static RegistryObject<Block> yellow_tulip = BLOCKS.register("yellow_tulip", () -> new Flower("yellow_tulip"));
    public static RegistryObject<Block> blue_tulip = BLOCKS.register("blue_tulip", () -> new Flower("blue_tulip"));
    public static RegistryObject<Block> black_tulip = BLOCKS.register("black_tulip", () -> new Flower("black_tulip"));
    public static RegistryObject<Block> green_tulip = BLOCKS.register("green_tulip", () -> new Flower("green_tulip"));
    public static RegistryObject<Block> purple_tulip = BLOCKS.register("purple_tulip", () -> new Flower("purple_tulip"));

    /**
     * Fences & Gates
     */
    public static RegistryObject<Block> dark_nether_bricks_fence = BLOCKS.register("dark_nether_bricks_fence", () -> new Fence("dark_nether_bricks_fence", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabSmallerBuildingBlocks, 2.0F, 30.0F));
    public static RegistryObject<Block> red_nether_bricks_fence = BLOCKS.register("red_nether_bricks_fence", () -> new Fence("red_nether_bricks_fence", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.NETHERRACK, ModTabs.creativeTabSmallerBuildingBlocks, 2.0F, 30.0F));
    public static RegistryObject<Block> nether_bricks_fence_gate = BLOCKS.register("nether_bricks_fence_gate", () -> new FenceGate("nether_bricks_fence_gate", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks, 2.0F, 30.0F));
    public static RegistryObject<Block> dark_nether_bricks_fence_gate = BLOCKS.register("dark_nether_bricks_fence_gate", () -> new FenceGate("dark_nether_bricks_fence_gate", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabSmallerBuildingBlocks, 2.0F, 30.0F));
    public static RegistryObject<Block> red_nether_bricks_fence_gate = BLOCKS.register("red_nether_bricks_fence_gate", () -> new FenceGate("red_nether_bricks_fence_gate", Material.ROCK, SoundType.STONE, "pickaxe", 0, MaterialColor.BLACK, ModTabs.creativeTabSmallerBuildingBlocks, 2.0F, 30.0F));

    /**
     * Walls
     */
    public static RegistryObject<Block> iron_wall = BLOCKS.register("iron_wall", () -> new ModWall("iron_wall", Blocks.IRON_BLOCK, 5.0F, 30.0F, MaterialColor.IRON, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> gold_wall = BLOCKS.register("gold_wall", () -> new ModWall("gold_wall", Blocks.GOLD_BLOCK, 5.0F, 30.0F, MaterialColor.GOLD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diamond_wall = BLOCKS.register("diamond_wall", () -> new ModWall("diamond_wall", Blocks.DIAMOND_BLOCK, 5.0F, 30.0F, MaterialColor.DIAMOND, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> emerald_wall = BLOCKS.register("emerald_wall", () -> new ModWall("emerald_wall", Blocks.EMERALD_BLOCK, 5.0F, 30.0F, MaterialColor.EMERALD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> quartz_wall = BLOCKS.register("quartz_wall", () -> new ModWall("quartz_wall", Blocks.QUARTZ_BLOCK, 0.8F, 4.0F, MaterialColor.QUARTZ, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> copper_wall = BLOCKS.register("copper_wall", () -> new ModWall("copper_wall", ModBlocks.copper_block.get(), 5.0F, 30.0F, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> tin_wall = BLOCKS.register("tin_wall", () -> new ModWall("tin_wall", ModBlocks.tin_block.get(), 5.0F, 30.0F, MaterialColor.IRON, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> bronze_wall = BLOCKS.register("bronze_wall", () -> new ModWall("bronze_wall", ModBlocks.bronze_block.get(), 5.0F, 30.0F, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> jade_wall = BLOCKS.register("jade_wall", () -> new ModWall("jade_wall", ModBlocks.jade_block.get(), 6.0F, 35.0F, MaterialColor.EMERALD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> amethyst_wall = BLOCKS.register("amethyst_wall", () -> new ModWall("amethyst_wall", ModBlocks.amethyst_block.get(), 6.0F, 35.0F, MaterialColor.PURPLE, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> stone_wall = BLOCKS.register("stone_wall", () -> new ModWall("stone_wall", Blocks.STONE, 1.5F, 30.0F, MaterialColor.STONE, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> granite_wall = BLOCKS.register("granite_wall", () -> new ModWall("granite_wall", Blocks.STONE, 1.5F, 30.0F, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> andesite_wall = BLOCKS.register("andesite_wall", () -> new ModWall("andesite_wall", Blocks.STONE, 1.5F, 30.0F, MaterialColor.STONE, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diorite_wall = BLOCKS.register("diorite_wall", () -> new ModWall("diorite_wall", Blocks.STONE, 1.5F, 30.0F, MaterialColor.IRON, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> basalt_wall = BLOCKS.register("basalt_wall", () -> new ModWall("basalt_wall", Blocks.STONE, 1.5F, 30.0F, MaterialColor.BLACK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> brick_wall = BLOCKS.register("brick_wall", () -> new ModWall("brick_wall", Blocks.BRICKS, 2.0F, 30.0F, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> stonebrick_wall = BLOCKS.register("stonebrick_wall", () -> new ModWall("stonebrick_wall", Blocks.STONE_BRICKS, 1.5F, 30.0F, MaterialColor.STONE, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> granite_bricks_wall = BLOCKS.register("granite_bricks_wall", () -> new ModWall("granite_bricks_wall", ModBlocks.granite_bricks.get(), 1.5F, 30.0F, MaterialColor.RED, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> andesite_bricks_wall = BLOCKS.register("andesite_bricks_wall", () -> new ModWall("andesite_bricks_wall", ModBlocks.andesite_bricks.get(), 1.5F, 30.0F, MaterialColor.STONE, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diorite_bricks_wall = BLOCKS.register("diorite_bricks_wall", () -> new ModWall("diorite_bricks_wall", ModBlocks.diorite_bricks.get(), 1.5F, 30.0F, MaterialColor.IRON, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> basalt_bricks_wall = BLOCKS.register("basalt_bricks_wall", () -> new ModWall("basalt_bricks_wall", ModBlocks.basalt_bricks.get(), 1.5F, 30.0F, MaterialColor.BLACK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> sandy_stone_bricks_wall = BLOCKS.register("sandy_stone_bricks_wall", () -> new ModWall("sandy_stone_bricks_wall", ModBlocks.basalt_bricks.get(), 1.5F, 30.0F, MaterialColor.SAND, ModTabs.creativeTabSmallerBuildingBlocks));

    /**
     * Stairs
     */
    public static RegistryObject<Block> coal_stairs = BLOCKS.register("coal_stairs", () -> new ModStairs("coal_stairs", Blocks.COAL_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> iron_stairs = BLOCKS.register("iron_stairs", () -> new ModStairs("iron_stairs", Blocks.IRON_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> gold_stairs = BLOCKS.register("gold_stairs", () -> new ModStairs("gold_stairs", Blocks.GOLD_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> lapis_stairs = BLOCKS.register("lapis_stairs", () -> new ModStairs("lapis_stairs", Blocks.LAPIS_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> redstone_stairs = BLOCKS.register("redstone_stairs", () -> new ModStairs("redstone_stairs", Blocks.REDSTONE_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diamond_stairs = BLOCKS.register("diamond_stairs", () -> new ModStairs("diamond_stairs", Blocks.DIAMOND_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> emerald_stairs = BLOCKS.register("emerald_stairs", () -> new ModStairs("emerald_stairs", Blocks.EMERALD_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> tin_stairs = BLOCKS.register("tin_stairs", () -> new ModStairs("tin_stairs", ModBlocks.tin_block.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> copper_stairs = BLOCKS.register("copper_stairs", () -> new ModStairs("copper_stairs", ModBlocks.copper_block.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> bronze_stairs = BLOCKS.register("bronze_stairs", () -> new ModStairs("bronze_stairs", ModBlocks.bronze_block.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> jade_stairs = BLOCKS.register("jade_stairs", () -> new ModStairs("jade_stairs", ModBlocks.jade_block.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> amethyst_stairs = BLOCKS.register("amethyst_stairs", () -> new ModStairs("amethyst_stairs", ModBlocks.amethyst_block.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> stone_stairs = BLOCKS.register("stone_stairs", () -> new ModStairs("stone_stairs", Blocks.STONE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> granite_stairs = BLOCKS.register("granite_stairs", () -> new ModStairs("granite_stairs", Blocks.STONE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> andesite_stairs = BLOCKS.register("andesite_stairs", () -> new ModStairs("andesite_stairs", Blocks.STONE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diorite_stairs = BLOCKS.register("diorite_stairs", () -> new ModStairs("diorite_stairs", Blocks.STONE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> basalt_stairs = BLOCKS.register("basalt_stairs", () -> new ModStairs("basalt_stairs", ModBlocks.basalt.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> granite_bricks_stairs = BLOCKS.register("granite_bricks_stairs", () -> new ModStairs("granite_bricks_stairs", ModBlocks.granite_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> andesite_bricks_stairs = BLOCKS.register("andesite_bricks_stairs", () -> new ModStairs("andesite_bricks_stairs", ModBlocks.andesite_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> diorite_bricks_stairs = BLOCKS.register("diorite_bricks_stairs", () -> new ModStairs("diorite_bricks_stairs", ModBlocks.diorite_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> basalt_bricks_stairs = BLOCKS.register("basalt_bricks_stairs", () -> new ModStairs("basalt_bricks_stairs", ModBlocks.basalt_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> sandy_stone_bricks_stairs = BLOCKS.register("sandy_stone_bricks_stairs", () -> new ModStairs("sandy_stone_bricks_stairs", ModBlocks.sandy_stone_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> oak_log_stairs = BLOCKS.register("oak_log_stairs", () -> new ModStairs("oak_log_stairs", Blocks.OAK_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> birch_log_stairs = BLOCKS.register("birch_log_stairs", () -> new ModStairs("birch_log_stairs", Blocks.BIRCH_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> spruce_log_stairs = BLOCKS.register("spruce_log_stairs", () -> new ModStairs("spruce_log_stairs", Blocks.SPRUCE_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> jungle_log_stairs = BLOCKS.register("jungle_log_stairs", () -> new ModStairs("jungle_log_stairs", Blocks.JUNGLE_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> acacia_log_stairs = BLOCKS.register("acacia_log_stairs", () -> new ModStairs("acacia_log_stairs", Blocks.ACACIA_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> dark_oak_log_stairs = BLOCKS.register("dark_oak_log_stairs", () -> new ModStairs("dark_oak_log_stairs", Blocks.DARK_OAK_LOG.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_oak_log_stairs = BLOCKS.register("seamless_oak_log_stairs", () -> new ModStairs("seamless_oak_log_stairs", ModBlocks.seamless_oak_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_birch_log_stairs = BLOCKS.register("seamless_birch_log_stairs", () -> new ModStairs("seamless_birch_log_stairs", ModBlocks.seamless_birch_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_spruce_log_stairs = BLOCKS.register("seamless_spruce_log_stairs", () -> new ModStairs("seamless_spruce_log_stairs", ModBlocks.seamless_spruce_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_jungle_log_stairs = BLOCKS.register("seamless_jungle_log_stairs", () -> new ModStairs("seamless_jungle_log_stairs", ModBlocks.seamless_jungle_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_acacia_log_stairs = BLOCKS.register("seamless_acacia_log_stairs", () -> new ModStairs("seamless_acacia_log_stairs", ModBlocks.seamless_acacia_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_dark_oak_log_stairs = BLOCKS.register("seamless_dark_oak_log_stairs", () -> new ModStairs("seamless_dark_oak_log_stairs", ModBlocks.seamless_dark_oak_log.get().getDefaultState(), Material.WOOD, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_smooth_sandstone_stairs = BLOCKS.register("seamless_smooth_sandstone_stairs", () -> new ModStairs("seamless_smooth_sandstone_stairs", ModBlocks.seamless_smooth_sandstone.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> seamless_smooth_red_sandstone_stairs = BLOCKS.register("seamless_smooth_red_sandstone_stairs", () -> new ModStairs("seamless_smooth_red_sandstone_stairs", ModBlocks.seamless_smooth_red_sandstone.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> prismarine_stairs = BLOCKS.register("prismarine_stairs", () -> new ModStairs("prismarine_stairs", Blocks.PRISMARINE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> prismarine_bricks_stairs = BLOCKS.register("prismarine_bricks_stairs", () -> new ModStairs("prismarine_bricks_stairs", Blocks.PRISMARINE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> dark_prismarine_stairs = BLOCKS.register("dark_prismarine_stairs", () -> new ModStairs("dark_prismarine_stairs", Blocks.PRISMARINE.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> obsidian_stairs = BLOCKS.register("obsidian_stairs", () -> new ModStairs("obsidian_stairs", Blocks.OBSIDIAN.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> end_stone_bricks_stairs = BLOCKS.register("end_stone_bricks_stairs", () -> new ModStairs("end_stone_bricks_stairs", Blocks.END_STONE_BRICKS.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> bone_stairs = BLOCKS.register("bone_stairs", () -> new ModStairs("bone_stairs", Blocks.BONE_BLOCK.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> red_nether_bricks_stairs = BLOCKS.register("red_nether_bricks_stairs", () -> new ModStairs("red_nether_bricks_stairs", Blocks.RED_NETHER_BRICKS.getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));
    public static RegistryObject<Block> dark_nether_bricks_stairs = BLOCKS.register("dark_nether_bricks_stairs", () -> new ModStairs("dark_nether_bricks_stairs", ModBlocks.dark_nether_bricks.get().getDefaultState(), Material.ROCK, ModTabs.creativeTabSmallerBuildingBlocks));

}